use test               
db.users.insert({username:"jones"})
db.users.find()
db.users.save({username:"smith"})
db.users.count()
db.users.find({username:"jones"})
db.users.update({username:"smith"}, {$set:{country:"canada"}})
db.users.update({username:"smith"}, {$set:{favorities:{cities:["chicago", "rome"],movies["matrix", "the sting"]}}})
db.users.update({username:"smith"}, {$unset:{country:1}})
db.users.update({username:"jones"}, {$set:{favorities:{movies:["rocky", "winter"]}}})
db.users.find({"favorities.movies":"matrix"})
db.users.update({"favorities.movies":"matrix"}, {$addToSet:{favorities.movies:"matrix2"}}, false, true)
db.users.remove({"favorities.cities":"rome"})
for(i=0; i<200000; i++){db.number.save({num:i});}
db.number.count()
db.number.find({num:500})
db.number.find({num:{$gt:199995}})
db.number.find({num:{$gt:20, $lt:25}})
db.number.find({num:{$gt:199995}}).explain()
db.number.createIndex({num:1});     db.number.getIndexes();  // проверить поиск с индексом
show dbs
show collections
db.stats()
db.help()
db.users.help()
db.number.save
db.users.insert({username:"tom", age:28, languages:["english", "german"]})
document=({username:"bill", age:32, languages:["english", "french"]});   db.users.insert(document)
db.createCollection("profile", {capped:true, size:500, max:150})
db.users.insert({username:"tom", age:32, languages:["english"]})
db.users.find({username:"tom"})
db.users.find({languages:"german"})
db.users.find({username:"tom", age:32})
db.users.find({username:"tom"}, {age:1})
db.users.find({username:"tom"}, {age:true, _id:false})
db.users.insert({username:"alex", age:28, company:{name:"microsoft", country:"usa"}})
db.users.find().limit(3)
db.users.find().skip(2)
db.users.find().sort({username:1})
db.users.find().sort({username:1}).skip(1).limit(2)
db.users.find().sort({$natural:-1}).limit
db.users.find({username:"tom"}, {languages:{$slice:1}})
db.users.find({username:"tom"}, {languages:{$slice:[-1,1]}})
db.users.find({}, {username:1})
db.users.find({},{username:1})   //???????????????
db.users.find({username:"tom"}).count()
db.users.find({username:"tom"}).skip(2).count(true)
db.users.distinct("username")
db.profile.remove({})
db.profile.drop()
db.users.find({username:"tom"}, {languages:{$slice:1}})
db.users.find({username:"tom"}, {languages:{$slice:[-1,1]}})
db.users.find({age:{$ne:22}})
db.users.find({age:{$in:[22, 32]}})
db.users.find({age:{$nin:[22, 32]}})
db.users.find({languages:{$all:["english", "french"]}})
db.users.find({$or:[{username:"tom"}, {age:22}]})
db.users.find({username:"tom", $or:[{age:22}, {languages:"german"}]})
db.users.find({languages:{$size:2}})
db.users.find({company:{$exists:true}})
db.users.find({username:{$regex:"^b"}})
db.users.save({username:"eugene", age:29, languages:["english", "spanish", "french"]})
db.users.update({username:"tom"}, {username:"tom", age:25, married:false}, {upsert:true})
db.users.update({username:"eugene", age:29}, {$set:{age:30}})
db.users.update({username:"tom"}, {$set:{username:"tom", age:25, married:false}}, {multi:true})
db.users.update({username:"tom"}, {$inc:{salary:100}})
db.users.update({username:"tom"}, {$unset:{salary:1}})
db.users.update({username:"tom"}, {$unset:{salary:1, age:1}})
db.users.update({username:"tom"}, {$addToSet:{languages:"spanish"}})
db.users.update({username:"tom"}, {$addToSet:{languages:{$each:["russian", "italian"]}}})
db.users.update({username:"tom"}, {$pop:{languages:-1}})
db.users.update({username:"tom"}, {$pull:{languages:"russian"}})
db.users.update({username:"tom"}, {$pullAll:{languages:["english", "french", "german"]}})
db.users.remove({age:{$lt:30}})
db.users.remove({username:"tom"}, true)